#! /usr/bin/env python3
#   script generated by source_obsnum.sh
import os
import sys

from lmtoy import runs

project="2018S1SEQUOIACommissioning"

# Dictionary of sources, each with a list of obsnum's in this project
# negative obsnums are ignored in the combinations. See also comments.txt
# for obsnum specific comments and parameters!
on = {}
on['NGC628']    = [ 80043, 80045, 80087, 80089, 80091, 80093, 80097, 80099, 80101]
on['IRC+10216'] = [ 79448, 82695, ]

# 76406 	79448

on['test+10216'] = [-76400,-76402,-76404,-76405, 76406, 77385, 77387, 77389,-77493,  # 2018
                    -77495,-77497, 77499,-77500, 77501, 77502, 77503, 77504,
                     77715,-77717, 77719, 77722, 77723, 77725, 77727, 77729, 77731,
                    -77733, 77735, 77736, 77737,-77818,-77820,-77990, 77992, 77994,
                     77996, 77998,-78063,-78063, 78065, 79440, 79442, 79444, 79446,
                     79448,
                     82666, 82668,-82695,
                     95121, 95123, 95125,    # 2022
                    100034, 100035, 100037,
                   -111259,                  # 2024
                    ]

on['IRC+10216_13CO'] = [ 76410, 77506, 77507, 77508, 77510 ]


# parameters for the first pass of the pipeline (restart=1 is automatically enforced here)
pars1 = {}

pars1['NGC628']         = ""
pars1['IRC+10216']      = "map_coord_use=1 public=2020-12-31"
pars1['IRC+10216_13CO'] = "map_coord_use=1 public=2020-12-31"
pars1['test+10216']     = "map_coord_use=1 dv=350 dw=650"



# parameters for the (optional) second pass of the pipeline (e.g. for bank=0)
pars2 = {}
pars2['IRC+10216']      = "qagrade=3"
pars2['IRC+10216_13CO'] = ""
pars2['test+10216']     = ""

# parameters for the (optional) third pass of the pipeline (usually for bank=1)
pars3 = {}


# Found 0 source(s) for 2018S1SEQUOIACommissioning

if __name__ == "__main__":
    runs.mk_runs(project, on, pars1, pars2, pars3, sys.argv)
